Repository armosec/system-tests, pull requests merged in 2023-08, with the labels that each got.

#131 Add tests for scanning scope
  configurations/ks-custom-fw/system-test-framework-scanning-cluster-and-file-scope.json
  configurations/ks-custom-fw/system-test-framework-scanning-file-scope.json
  configurations/ks-custom-fw/system-test-framework-scanning-scope.json
  configurations/system/tests_cases/kubescape_tests.py
  tests_scripts/kubescape/base_kubescape.py
  tests_scripts/kubescape/scan.py
Labels: Tests

#148 Default Learning Period
  infrastructure/helm_wrapper.py
  tests_scripts/helm/base_helm.py
Labels: enhancement, Refactoring

#140 unified configuration system test
  configurations/system/tests_cases/kubescape_tests.py
  systest_utils/statics.py
  tests_scripts/kubescape/base_kubescape.py
  tests_scripts/kubescape/config.py
Labels: AI

#163 use ready state in get_running_pods
  tests_scripts/helm/base_vulnerability_scanning.py
  tests_scripts/helm/vulnerability_scanning.py
  tests_scripts/kubernetes/base_k8s.py
Labels: Refactoring

#165 print non running pods on failure in verify_running_pods
  tests_scripts/kubernetes/base_k8s.py
Labels: enhancement
