Repository armosec/system-tests, pull requests merged in 2023-10, with the labels that each got.

#180 fix: print last scan time
  infrastructure/backend_api.py
Labels: Bug fix

#182 fix: current time acquisition
  infrastructure/backend_api.py
  tests_scripts/helm/ks_microservice.py
Labels: Bug fix

#183 Do not assert on more than one connected cluster
  tests_scripts/helm/base_vulnerability_scanning.py
Labels: Tests

#184 Update base_vulnerability_scanning.py
  tests_scripts/helm/base_vulnerability_scanning.py
Labels: enhancement

#185 Revert "Update base_vulnerability_scanning.py"
  tests_scripts/helm/base_vulnerability_scanning.py
Labels: Refactoring

#186 Update base_vulnerability_scanning.py
  tests_scripts/helm/base_vulnerability_scanning.py
Labels: Refactoring

#187 Update base_vulnerability_scanning.py
  tests_scripts/helm/base_vulnerability_scanning.py
Labels: Refactoring

#188 Update base_vulnerability_scanning.py
  tests_scripts/helm/base_vulnerability_scanning.py
Labels: Refactoring

#190 ci: add attack-chain cronjob test
  jenkins_files/Jenkinsfile-helm-ks-be.groovy
Labels: Tests

#191 Update base_vulnerability_scanning.py
  tests_scripts/helm/base_vulnerability_scanning.py
Labels: Tests

#193 fix: update expected value
  configurations/attack_chains_expected_values/alpine.json
  requirements.txt
  tests_scripts/helm/ks_microservice.py
Labels: Bug fix

#194 changed url-config
  systest_utils/statics.py
Labels: Refactoring

#196 Update ks_microservice.py
  tests_scripts/helm/ks_microservice.py
Labels: enhancement

#197 chore: update ac responses
  configurations/attack_chains_expected_values/attack-chain-1-1.json
  configurations/attack_chains_expected_values/attack-chain-5.json
Labels: Refactoring

#198 Update base_vulnerability_scanning.py
  tests_scripts/helm/base_vulnerability_scanning.py
Labels: Refactoring

#199 Update base_vulnerability_scanning.py
  tests_scripts/helm/base_vulnerability_scanning.py
Labels: Refactoring

#201 Update base_vulnerability_scanning.py
  tests_scripts/helm/base_vulnerability_scanning.py
Labels: Refactoring

#202 Revert "changed url-config"
  systest_utils/statics.py
Labels: Bug fix

#204 fix: update test expected output
  configurations/attack_chains_expected_values/attack-chain-3.json
Labels: Bug fix

#205 support access keys
  infrastructure/backend_api.py
  infrastructure/backendapi.md
  infrastructure/helm_wrapper.py
  systest_utils/systests_utilities.py
  tests_scripts/base_test.py
  tests_scripts/helm/base_helm.py
  tests_scripts/kubescape/base_kubescape.py
Labels: enhancement
