Repository armosec/system-tests, pull requests merged in 2023-09, with the labels that each got.

#164 Support new helm chart and Kubescape version
  configurations/system/backends.py
  infrastructure/helm_wrapper.py
  tests_scripts/helm/base_helm.py
  tests_scripts/kubescape/base_kubescape.py
Labels: Refactoring

#167 Support kubescape-operator helm chart
  configurations/system/tests_cases/vulnerability_scanning_tests.py
  systest_utils/statics.py
  tests_scripts/helm/base_vulnerability_scanning.py
Labels: Refactoring

#170 fix don't fail on cleanup
  tests_scripts/kubescape/scan.py
Labels: Bug fix

#171 add MS Teams test + secrets
  jenkins_files/Jenkinsfile-helm-ks-be.groovy
  jenkins_files/Jenkinsfile_single_test.groovy
Labels: enhancement

#174 Fix configurations test
  tests_scripts/kubescape/base_kubescape.py
  tests_scripts/kubescape/scan.py
Labels: enhancement, Tests

#175 feat: add image fix scenarios
  configurations/attack-chains-test-env/alpine/01-alpine.yaml
  configurations/attack-chains-test-env/alpine/fix_control
  configurations/attack-chains-test-env/alpine/fix_image
  configurations/attack_chains_expected_values/alpine.json
  configurations/system/tests_cases/ks_microservice_test.py
  readme.md
  tests_scripts/helm/ks_microservice.py
Labels: enhancement, Tests

#176 Control cluster from cli
  configurations/system/tests_cases/ks_microservice_test.py
  tests_scripts/helm/ks_microservice.py
  tests_scripts/kubernetes/base_k8s.py
  tests_scripts/kubescape/base_kubescape.py
Labels: Tests

#178 Test ac systests eran
  configurations/system/tests_cases/ks_microservice_test.py
  jenkins_files/Jenkinsfile-helm-ks-be-test.groovy
  readme.md
Labels: Refactoring

#177 test: add attack chain test scenarios
  configurations/attack-chains-test-env/alpine/01-alpine.yaml
  configurations/attack_chains_expected_values/attack-chain-3.json
  configurations/attack_chains_expected_values/attack-chain-6.json
  configurations/system/tests_cases/ks_microservice_test.py
  jenkins_files/Jenkinsfile-helm-ks-be-test.groovy
  jenkins_files/Jenkinsfile-helm-ks-be.groovy
  readme.md
  tests_scripts/helm/base_helm.py
  tests_scripts/helm/ks_microservice.py
Labels: Tests

#179 fix: improve management of utc dates
  infrastructure/backend_api.py
Labels: Bug fix
