Repository armosec/system-tests, pull requests merged in 2024-05, with the labels that each got.

#338 Fixed test - install the chart
  tests_scripts/helm/ks_microservice.py
Labels: enhancement, Tests

#337 add security risk system test for networkpolicy control
  configurations/scenarios_expected_values/attack-chain-5_security-risks-resources_sidebar_R0007.json
  configurations/system/tests_cases/security_risks_tests.py
  readme.md
  system_test_mapping.json
  systest_utils/scenarios_manager.py
  tests_scripts/helm/ks_microservice.py
Labels: enhancement, Tests, Review effort [1-5]: 3

#340 Update systests repos map
  system_test_mapping.json
Labels: enhancement, Review effort [1-5]: 1

#341 Add verification step for exception deletion after resource deletionin ks_microservice.py
  tests_scripts/helm/ks_microservice.py
Labels: enhancement, Tests, Review effort [1-5]: 2

#342 check cluster scan status, not global field
  systest_utils/scenarios_manager.py
Labels: bug_fix, Review effort [1-5]: 1

#343 use random name for user alert channel test
  tests_scripts/users_notifications/alert_channels.py
Labels: enhancement, Tests, Review effort [1-5]: 2

#344 Support dns backwards compatibility
  tests_scripts/helm/base_network_policy.py
Labels: enhancement

#345 Increase timeout for waiting for response from BE in AttackChainsScen…
  systest_utils/scenarios_manager.py
Labels: enhancement, Review effort [1-5]: 1

#346 adapt incident basic test
  system_test_mapping.json
  tests_scripts/runtime/incidents.py
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#347 fix basic_incident_presented
  infrastructure/kubectl_wrapper.py
  tests_scripts/runtime/incidents.py
Labels: enhancement, Review effort [1-5]: 2

#348 Update system_test_mapping.json
  system_test_mapping.json
Labels: enhancement, Review effort [1-5]: 2

#354 chore: Fix sleep duration for triggering scan in helm tests
  tests_scripts/helm/ks_microservice.py
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#356 chore: Fix sleep duration for triggering scan in helm tests
  tests_scripts/helm/ks_microservice.py
Labels: enhancement, Review effort [1-5]: 1

#360 update expected components
  tests_scripts/helm/vuln_scan.py
Labels: enhancement, Tests, Review effort [1-5]: 2

#362 add ac_8_fix_control_with_relevancy
  configurations/scenarios-test-env/README.md
  configurations/scenarios-test-env/attack-chain-8/01-exposed-dp.yaml
  configurations/scenarios-test-env/attack-chain-8/02-rbac-permissions.yaml
  configurations/scenarios-test-env/attack-chain-8/README.md
  configurations/scenarios-test-env/attack-chain-8/fix_control
  configurations/scenarios-test-env/attack-chain-8/kind-config
  configurations/scenarios_expected_values/attack-chain-8.json
  configurations/system/tests_cases/ks_microservice_test.py
  readme.md
  system_test_mapping.json
  systest_utils/scenarios_manager.py
Labels: enhancement, Tests, Review effort [1-5]: 3

#363 fix related resources check
  systest_utils/scenarios_manager.py
Labels: bug_fix, Review effort [1-5]: 2

#364 fix scenario to create only 1 a.c
  configurations/scenarios-test-env/attack-chain-8/01-exposed-dp.yaml
  configurations/scenarios-test-env/attack-chain-8/README.md
Labels: enhancement, Review effort [1-5]: 2

#365 fix for nil slices, update nginx NN
  configurations/network-policy/expected-generated-network-policy/deployment-nginx-basic.json
  configurations/network-policy/expected-generated-network-policy/deployment-nginx.json
  tests_scripts/helm/base_network_policy.py
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#355 Update system_test_mapping.json
  system_test_mapping.json
Labels: enhancement, Review effort [1-5]: 1

#366 fix expected
  configurations/scenarios_expected_values/attack-chain-8.json
Labels: enhancement, Review effort [1-5]: 2

#314 Jira
  configurations/expected-result/integrations/expectedJiraSchema.json
  configurations/integrations/issueTmpl.json
  configurations/k8s_workloads/integrations/nginx-deployment.yaml
  configurations/system/tests.py
  configurations/system/tests_cases/integrations_tests.py
  infrastructure/backend_api.py
  system_test_mapping.json
  systest_utils/statics.py
  tests_scripts/helm/jira_integration.py
Labels: enhancement, Tests, Review effort [1-5]: 3

#367 enable test
  system_test_mapping.json
Labels: Review effort [1-5]: 1, configuration changes

#368 Create test workload before installing helm
  infrastructure/backend_api.py
  tests_scripts/helm/jira_integration.py
Labels: enhancement, Tests, Review effort [1-5]: 2

#369 wait for status to be updated to done before triggering another scan
  tests_scripts/helm/ks_microservice.py
Labels: enhancement, Review effort [1-5]: 2

#371 adjust resources
  configurations/scenarios-test-env/attack-chain-8/01-exposed-dp.yaml
Labels: enhancement, Review effort [1-5]: 1

#372 fix: Add delay before triggering scan in ScanSecurityRisksExceptionsW…
  tests_scripts/helm/ks_microservice.py
Labels: Tests, Bug fix, Review effort [1-5]: 2

#373 chore: Refactor get_security_risks_list method in ControlPanelAPI
  infrastructure/backend_api.py
  tests_scripts/helm/jira_integration.py
Labels: enhancement, Tests, Review effort [1-5]: 3

#380 treat delete tenant as success - temporary
  infrastructure/backend_api.py
  tests_scripts/base_test.py
Labels: Tests, Bug fix, Review effort [1-5]: 2

#381 added a sleep and additional logs for the np test
  tests_scripts/helm/base_network_policy.py
  tests_scripts/helm/network_policy.py
Labels: enhancement, Tests, Review effort [1-5]: 2

#382 fix proxy helm wrapper
  infrastructure/helm_wrapper.py
Labels: Bug fix

#384 Remove deprecated calls
  tests_scripts/helm/base_vuln_scan.py
  tests_scripts/helm/ks_microservice.py
  tests_scripts/helm/vuln_scan.py
Labels: enhancement, Tests

#386 remove vuln_scan_trigger_scan_on_new_image system test
  configurations/system/tests_cases/vuln_scan_tests.py
  jenkins_files/Jenkinsfile-helm-ks-be-test.groovy
  jenkins_files/Jenkinsfile-helm-ks-be.groovy
  jenkins_files/Jenkinsfile_helm_chart.groovy
  jenkins_files/Jenkinsfile_helm_chart_on_going_features.groovy
  jenkins_files/Jenkinsfile_payment.groovy
  jenkins_files/Jenkinsfile_relevancy.groovy
  readme.md
  system_test_mapping.json
Labels: enhancement, Tests, Review effort [1-5]: 2

#387 adding timeout fix
  tests_scripts/helm/network_policy.py
Labels: Bug fix, Review effort [1-5]: 2

#388 add mroe time
  tests_scripts/helm/network_policy.py
Labels: Tests, Review effort [1-5]: 1

#389 sr timeout fix + NP fixes
  tests_scripts/helm/ks_microservice.py
  tests_scripts/helm/network_policy.py
Labels: Bug fix, Review effort [1-5]: 2
