Repository armosec/system-tests, pull requests merged in 2024-03, with the labels that each got.

#275 Vuln v2 views apis test
  configurations/expected-result/V2_VIEWS/cve_details.json
  configurations/expected-result/V2_VIEWS/image_details.json
  configurations/expected-result/V2_VIEWS/kev_vulan.json
  configurations/expected-result/V2_VIEWS/wl_details.json
  configurations/expected-result/V2_VIEWS/wl_filtered.json
  configurations/k8s_workloads/config-map/viewsv2/wikijs-ingress.yaml
  configurations/k8s_workloads/deployments/viewsv2/mariadb.yaml
  configurations/k8s_workloads/deployments/viewsv2/nginx-ingress-deployment.yaml
  configurations/k8s_workloads/deployments/viewsv2/wikijs.yaml
  configurations/k8s_workloads/services/viewsv2/mariadb.yaml
  configurations/k8s_workloads/services/viewsv2/nginx-ingress.yaml
  configurations/k8s_workloads/services/viewsv2/wikijs.yaml
  configurations/system/tests_cases/vuln_scan_tests.py
  infrastructure/backend_api.py
  infrastructure/helm_wrapper.py
  readme.md
  system_test_mapping.json
  systest_utils/systests_utilities.py
  tests_scripts/helm/base_helm.py
  tests_scripts/helm/base_vuln_scan.py
  tests_scripts/helm/vuln_scan.py
Labels: enhancement, Tests, Review effort [1-5]: 4

#276 Vuln views - Extend tm and add ignore image hash and repo
  configurations/system/tests_cases/vuln_scan_tests.py
  tests_scripts/helm/vuln_scan.py
Labels: enhancement, Tests, bug_fix, Review effort [1-5]: 3

#277 Fixvuln_v2_views test
  configurations/expected-result/V2_VIEWS/cve_details.json
  configurations/expected-result/V2_VIEWS/image_details.json
  configurations/expected-result/V2_VIEWS/wl_details.json
  configurations/expected-result/V2_VIEWS/wl_filtered.json
  configurations/k8s_workloads/config-map/viewsv2/wikijs-ingress.yaml
  configurations/k8s_workloads/deployments/viewsv2/httpdproxy.yaml
  configurations/k8s_workloads/deployments/viewsv2/nginx-ingress-deployment.yaml
  configurations/k8s_workloads/deployments/viewsv2/wikijs.yaml
  configurations/k8s_workloads/deployments/viewsv2kev/mariadb.yaml
  configurations/k8s_workloads/services/viewsv2/httpd.yaml
  configurations/k8s_workloads/services/viewsv2/wikijs.yaml
  configurations/k8s_workloads/services/viewsv2kev/mariadb.yaml
  configurations/system/tests_cases/vuln_scan_tests.py
  tests_scripts/helm/vuln_scan.py
Labels: enhancement, Tests, Review effort [1-5]: 2

#282 Update system_test_mapping.json
  system_test_mapping.json
Labels: enhancement, Review effort [1-5]: 1

#283 Update system_test_mapping.json
  system_test_mapping.json
Labels: enhancement, Review effort [1-5]: 2

#286 fix validate_expected_network_neighbors
  tests_scripts/helm/base_network_policy.py
Labels: bug_fix, Review effort [1-5]: 2

#290 disable CSV verification through ws for kubescape release
  tests_scripts/kubescape/scan.py
Labels: Tests, Review effort [1-5]: 1

#292 add 2 min delay to slack test
  tests_scripts/users_notifications/alert_notifications.py
Labels: enhancement, Review effort [1-5]: 1

#291 Revert "disable CSV verification through ws for kubescape release"
  tests_scripts/kubescape/scan.py
Labels: enhancement, Review effort [1-5]: 2

#284 add smart remediation system tests
  configurations/k8s_workloads/smart-remediation/c0016-fixed.yaml
  configurations/k8s_workloads/smart-remediation/c0017-fixed.yaml
  configurations/k8s_workloads/smart-remediation/c0034-fixed.yaml
  configurations/k8s_workloads/smart-remediation/c0045-fixed.yaml
  configurations/k8s_workloads/smart-remediation/c0046-fixed.yaml
  configurations/k8s_workloads/smart-remediation/c0048-fixed.yaml
  configurations/k8s_workloads/smart-remediation/c0057-fixed.yaml
  configurations/k8s_workloads/smart-remediation/c0074-fixed.yaml
  configurations/k8s_workloads/smart-remediation/nginx-deployment.yaml
  configurations/system/tests.py
  configurations/system/tests_cases/smart_remediation_tests.py
  infrastructure/backend_api.py
  system_test_mapping.json
  systest_utils/statics.py
  tests_scripts/helm/smart_remediation.py
  tests_scripts/kubernetes/base_k8s.py
Labels: enhancement, Tests, Review effort [1-5]: 4

#295 add on prem backend to systest
  configurations/system/backends.py
  infrastructure/api_login.py
  infrastructure/backend_api.py
Labels: enhancement, Review effort [1-5]: 2

#296 fix synchronizer tests
  tests_scripts/helm/synchronizer.py
Labels: bug_fix
