Repository armosec/system-tests, pull requests merged in 2024-12, with the labels that each got.

#495 add envars to stage
  tests_scripts/workflows/conf_workflows.py
  tests_scripts/workflows/utils.py
Labels: Review effort [1-5]: 1

#496 fix conf workflow test
  tests_scripts/workflows/conf_workflows.py
Labels: Review effort [1-5]: 2

#497 added uniq name to workflows
  tests_scripts/workflows/jira_workflows.py
  tests_scripts/workflows/slack_workflows.py
  tests_scripts/workflows/teams_workflows.py
  tests_scripts/workflows/utils.py
Labels: Review effort [1-5]: 2

#498 revert func return
  infrastructure/backend_api.py
  tests_scripts/workflows/jira_workflows.py
  tests_scripts/workflows/utils.py
Labels: Review effort [1-5]: 2

#500 fix the jira test
  tests_scripts/workflows/jira_workflows.py
Labels: Review effort [1-5]: 1

#501 fix the jira test
  tests_scripts/workflows/jira_workflows.py
Labels: Review effort [1-5]: 2

#502 Workflows
  infrastructure/backend_api.py
  tests_scripts/workflows/conf_workflows.py
  tests_scripts/workflows/jira_workflows.py
  tests_scripts/workflows/teams_workflows.py
  tests_scripts/workflows/utils.py
Labels: Review effort [1-5]: 2

#504 update image gb-frontend for synchronizer test
  configurations/k8s_workloads/synchronizer/replicaset.yaml
Labels: Review effort [1-5]: 1

#505 Refactor workflow API methods to accept dynamic request bodies and im…
  infrastructure/backend_api.py
  tests_scripts/workflows/conf_workflows.py
  tests_scripts/workflows/jira_workflows.py
  tests_scripts/workflows/slack_workflows.py
  tests_scripts/workflows/teams_workflows.py
Labels: Review effort [1-5]: 3

#507 Update target repositories in system test mapping to use dummy versions
  system_test_mapping.json
Labels: Review effort [1-5]: 1

#506 add namespace to workflows tests
  configurations/system/tests_cases/workflows_tests.py
  configurations/workflows_notifications/deployments/http1/apache-http1.yaml
  configurations/workflows_notifications/deployments/http2/apache1-http2.yaml
  tests_scripts/workflows/jira_workflows.py
  tests_scripts/workflows/slack_workflows.py
  tests_scripts/workflows/teams_workflows.py
Labels: Review effort [1-5]: 1

#508 Update system test mapping to use dummy target repositories for testing
  system_test_mapping.json
Labels: Review effort [1-5]: 1

#511 add registry scanning system test
  configurations/registry/check_aws.json
  configurations/registry/check_azure.json
  configurations/registry/check_google.json
  configurations/registry/check_quay.json
  configurations/registry/create_quay.json
  configurations/system/tests.py
  configurations/system/tests_cases/registry_tests.py
  infrastructure/backend_api.py
  system_test_mapping.json
  systest_utils/statics.py
  tests_scripts/registry/__init__.py
  tests_scripts/registry/base_registry.py
  tests_scripts/registry/registry_connectors.py
Labels: Review effort [1-5]: 4

#510 Fix workflows tests
  configurations/system/tests_cases/workflows_tests.py
  infrastructure/backend_api.py
  tests_scripts/base_test.py
  tests_scripts/workflows/jira_workflows.py
  tests_scripts/workflows/slack_workflows.py
  tests_scripts/workflows/teams_workflows.py
  tests_scripts/workflows/utils.py
Labels: Review effort [1-5]: 3

#514 dis reg
  system_test_mapping.json
  tests_scripts/registry/registry_connectors.py
Labels: Review effort [1-5]: 2

#515 retry is_ks_cronjob_created_in_backend with wait_for_report
  infrastructure/backend_api.py
  tests_scripts/helm/ks_microservice.py
Labels: Review effort [1-5]: 2

#516 remove git commit check
  tests_scripts/kubescape/base_kubescape.py
Labels: Review effort [1-5]: 1

#517 remove server info checks with cli scans
  tests_scripts/kubescape/base_kubescape.py
Labels: Review effort [1-5]: 2

#519 add enrich_tickets parameter to vulnerability API methods for improve…
  infrastructure/backend_api.py
  tests_scripts/helm/jira_integration.py
  tests_scripts/workflows/jira_workflows.py
Labels: Review effort [1-5]: 2

#520 ignore tickets key
  systest_utils/scenarios_manager.py
Labels: Review effort [1-5]: 1

#521 add cluster and namespace to workflow scope configuration
  tests_scripts/workflows/conf_workflows.py
Labels: Review effort [1-5]: 1

#523 Fix 3
  infrastructure/backend_api.py
Labels: Review effort [1-5]: 1

#525 force nokollector branch in helm (temporary)
  tests_scripts/helm/base_helm.py
Labels: Review effort [1-5]: 1

#524 enable workflows tests
  system_test_mapping.json
Labels: Review effort [1-5]: 1

#526 No kollector
  tests_scripts/helm/base_helm.py
Labels: Review effort [1-5]: 1

#529 Remove 'production' environments from skip_on_environment in system t…
  system_test_mapping.json
Labels: Review effort [1-5]: 2

#531 enable registry tests
  system_test_mapping.json
Labels: Review effort [1-5]: 1

#534 extend registries APIs timeouts
  infrastructure/backend_api.py
Labels: Review effort [1-5]: 1

#536 enable registry tests
  tests_scripts/registry/registry_connectors.py
Labels: Review effort [1-5]: 2

#537 Add jiraCollaborationGUID parameter to workflow body builders for Jir…
  tests_scripts/workflows/jira_workflows.py
Labels: Review effort [1-5]: 2

#542 Add early exit condition for message retrieval in Teams workflows
  tests_scripts/workflows/teams_workflows.py
Labels: Review effort [1-5]: 1

#544 Update memory resource requests in WordPress YAML configurations to u…
  configurations/scenarios-test-env/attack-chain-1-1/03-wordpress.yaml
  configurations/scenarios-test-env/attack-chain-1-2/03-wordpress.yaml
  configurations/scenarios-test-env/attack-chain-2/03-wordpress.yaml
  configurations/scenarios-test-env/attack-chain-3/03-wordpress.yaml
  configurations/scenarios-test-env/attack-chain-4/03-wordpress.yaml
  configurations/scenarios-test-env/attack-chain-5/02-wordpress.yaml
  configurations/scenarios-test-env/attack-chain-6/02-wordpress.yaml
  configurations/scenarios-test-env/attack-chain-7/02-wordpress.yaml
  configurations/scenarios-test-env/attack-chain-9/02-service-unauthnticated.yaml
Labels: Review effort [1-5]: 1

#545 change the apis to support the multi jira
  configurations/integrations/issueTmpl.json
  infrastructure/backend_api.py
  tests_scripts/helm/jira_integration.py
  tests_scripts/workflows/jira_workflows.py
Labels: Review effort [1-5]: 3

#548 update target repositories in system_test_mapping.json to use dummy s…
  system_test_mapping.json
Labels: Review effort [1-5]: 1

#549 Testrunningpods
  tests_scripts/kubernetes/base_k8s.py
Labels: Review effort [1-5]: 2, Possible security concern
