Repository armosec/system-tests, pull requests merged in 2024-07, with the labels that each got.

#404 Fix Jira schema to remove unused "Reporter" field
  configurations/expected-result/integrations/expectedJiraSchema.json
  infrastructure/backend_api.py
  systest_utils/scenarios_manager.py
  tests_scripts/helm/jira_integration.py
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#397 sub-5140 - added generate system tests
  configurations/k8s_workloads/seccomp/alpine-seccomp-pod-overly-permissive-after-optimize.yaml
  configurations/system/tests_cases/seccomp_tests.py
  infrastructure/backend_api.py
  system_test_mapping.json
  tests_scripts/helm/seccomp.py
Labels: enhancement, Tests, Review effort [1-5]: 4

#408 jira integration add log of the result
  tests_scripts/helm/jira_integration.py
Labels: enhancement, Review effort [1-5]: 2

#407 update NP expected results
  configurations/network-policy/expected-generated-network-policy/busybox-known-server.json
  configurations/network-policy/expected-generated-network-policy/busybox.json
  configurations/network-policy/expected-generated-network-policy/deployment-mariadb-basic.json
  configurations/network-policy/expected-generated-network-policy/deployment-mariadb.json
  configurations/network-policy/expected-generated-network-policy/deployment-nginx-basic.json
  configurations/network-policy/expected-generated-network-policy/deployment-nginx.json
  configurations/network-policy/expected-generated-network-policy/deployment-wikijs-basic.json
  configurations/network-policy/expected-generated-network-policy/deployment-wikijs.json
  configurations/network-policy/expected-network-neighbors/busybox-known-server.json
  configurations/network-policy/expected-network-neighbors/busybox.json
  configurations/network-policy/expected-network-neighbors/deployment-mariadb-basic.json
  configurations/network-policy/expected-network-neighbors/deployment-mariadb.json
  configurations/network-policy/expected-network-neighbors/deployment-nginx-basic.json
  configurations/network-policy/expected-network-neighbors/deployment-nginx.json
  configurations/network-policy/expected-network-neighbors/deployment-wikijs-basic.json
  configurations/network-policy/expected-network-neighbors/deployment-wikijs.json
  tests_scripts/helm/base_network_policy.py
Labels: enhancement, Review effort [1-5]: 4

#409 Update system_test_mapping.json with correct repository names
  system_test_mapping.json
Labels: enhancement, Review effort [1-5]: 1

#410 chore: Update system_test_mapping.json with correct repository names
  system_test_mapping.json
Labels: enhancement, Review effort [1-5]: 1

#411 remove extra hosts in deployment-wikijs-basic
  configurations/network-policy/expected-network-neighbors/deployment-wikijs-basic.json
Labels: Bug fix, Review effort [1-5]: 1

#412 fix nil slices
  configurations/network-policy/expected-generated-network-policy/deployment-wikijs-basic.json
  configurations/network-policy/expected-network-neighbors/busybox-known-server.json
  configurations/network-policy/expected-network-neighbors/busybox.json
  configurations/network-policy/expected-network-neighbors/deployment-mariadb-basic.json
  configurations/network-policy/expected-network-neighbors/deployment-mariadb.json
  configurations/network-policy/expected-network-neighbors/deployment-nginx-basic.json
  configurations/network-policy/expected-network-neighbors/deployment-nginx.json
  configurations/network-policy/expected-network-neighbors/deployment-wikijs-basic.json
  configurations/network-policy/expected-network-neighbors/deployment-wikijs.json
Labels: Bug fix, Review effort [1-5]: 2

#413 remove nil dnsNames
  configurations/network-policy/expected-network-neighbors/busybox-known-server.json
  configurations/network-policy/expected-network-neighbors/busybox.json
  configurations/network-policy/expected-network-neighbors/deployment-mariadb-basic.json
  configurations/network-policy/expected-network-neighbors/deployment-mariadb.json
  configurations/network-policy/expected-network-neighbors/deployment-nginx-basic.json
  configurations/network-policy/expected-network-neighbors/deployment-wikijs-basic.json
  configurations/network-policy/expected-network-neighbors/deployment-wikijs.json
Labels: enhancement, Review effort [1-5]: 2

#414 fix log on assert failure
  tests_scripts/helm/base_network_policy.py
Labels: Bug fix, Review effort [1-5]: 1

#415 Update security risk category from "Workload configuration" to "Workl…
  configurations/scenarios_expected_values/attack-chain-5_security-risks-categories.json
  configurations/scenarios_expected_values/attack-chain-5_security-risks-exceptions-edit-response.json
  configurations/scenarios_expected_values/attack-chain-5_security-risks-exceptions-list.json
  configurations/scenarios_expected_values/attack-chain-5_security-risks-list.json
  configurations/scenarios_expected_values/attack-chain-5_security-risks-uv-category.json
Labels: enhancement, Review effort [1-5]: 2

#416 add helm dependency update for local installs
  infrastructure/helm_wrapper.py
  tests_scripts/helm/base_helm.py
Labels: enhancement, Tests, Review effort [1-5]: 2

#417 add appliedNetworkPolicyType to attack chain report
  configurations/scenarios_expected_values/attack-chain-5_security-risks-resources_sidebar_R0007.json
Labels: enhancement, Review effort [1-5]: 1

#418 Revert "chore: Update system_test_mapping.json with correct repository names"
  system_test_mapping.json
Labels: enhancement, Review effort [1-5]: 1

#421 chore: Add start method to VulnerabilityV2Views class
  tests_scripts/helm/vuln_scan.py
Labels: enhancement, Review effort [1-5]: 2

#423 chore: Update system_test_mapping.json with correct repository names
  system_test_mapping.json
Labels: enhancement, Review effort [1-5]: 1

#426 chore: combining smart remediation system test into one test
  configurations/system/tests_cases/smart_remediation_tests.py
  readme.md
  system_test_mapping.json
  tests_scripts/helm/smart_remediation.py
Labels: enhancement, Tests, Review effort [1-5]: 3

#427 chore: Update smart remediation tests for multiple controls
  tests_scripts/helm/smart_remediation.py
Labels: enhancement, Review effort [1-5]: 2

#428 chore: Update smart remediation tests for multiple controls
  tests_scripts/helm/smart_remediation.py
Labels: enhancement, Tests, Review effort [1-5]: 3

#429 Sm new test
  tests_scripts/helm/smart_remediation.py
Labels: enhancement, Tests, Review effort [1-5]: 3

#424 Sub 5260
  configurations/scenarios-test-env/README.md
  configurations/scenarios-test-env/attack-chain-9/01-crd.yaml
  configurations/scenarios-test-env/attack-chain-9/02-service-unauthnticated.yaml
  configurations/scenarios-test-env/attack-chain-9/README.md
  configurations/scenarios-test-env/attack-chain-9/fix_control
  configurations/scenarios-test-env/attack-chain-9/kind-config
  configurations/scenarios_expected_values/attack-chain-9.json
  configurations/system/tests_cases/ks_microservice_test.py
  system_test_mapping.json
Labels: enhancement, Tests, Review effort [1-5]: 3

#432 Refactor get_report_guid function to not wait for result
  tests_scripts/helm/ks_microservice.py
Labels: enhancement, Tests, Review effort [1-5]: 1

#431 chore: Update skip_on_environment value in system_test_mapping.json
  system_test_mapping.json
Labels: Review effort [1-5]: 1, configuration changes

#434 Increase the sleep time for deploying the scenario and applying the f…
  systest_utils/scenarios_manager.py
  tests_scripts/helm/ks_microservice.py
Labels: enhancement, Review effort [1-5]: 2
