Repository armosec/system-tests, pull requests merged in 2024-02, with the labels that each got.

#247 Patch default secrets
  infrastructure/helm_wrapper.py
  infrastructure/kubectl_wrapper.py
  tests_scripts/helm/base_helm.py
  tests_scripts/kubernetes/base_k8s.py
Labels: enhancement, Review effort [1-5]: 3

#248 fixed test
  tests_scripts/helm/vuln_scan.py
  tests_scripts/kubernetes/base_k8s.py
Labels: Bug fix, Review effort [1-5]: 1

#252 remove ac tests
  system_test_mapping.json
Labels: enhancement, Review effort [1-5]: 1

#253 NP tests - remove backend validation
  tests_scripts/helm/network_policy.py
Labels: enhancement, Review effort [1-5]: 2

#254 Remove unused code and update system test mapping
  configurations/system/tests_cases/kubescape_tests.py
  system_test_mapping.json
Labels: enhancement, Review effort [1-5]: 1

#255 Update system_test_mapping.json with dummy services
  system_test_mapping.json
Labels: enhancement, Review effort [1-5]: 1

#257 add log before reading slack messages
  tests_scripts/users_notifications/alert_notifications.py
Labels: enhancement, Review effort [1-5]: 1

#258 change env var name
  tests_scripts/users_notifications/alert_notifications.py
Labels: enhancement, Review effort [1-5]: 1

#260 remove LRU workaround, use temporary image
  build.sh
  configurations/k8s_workloads/synchronizer/replicaset.yaml
  configurations/k8s_workloads/synchronizer/statefulset.yaml
  create_env.sh
  run_tests.sh
  tests_scripts/helm/synchronizer.py
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#262 enable np tests
  system_test_mapping.json
Labels: enhancement, Review effort [1-5]: 2

#263 Adding tests to json mapping
  system_test_mapping.json
Labels: enhancement, Tests, Review effort [1-5]: 2

#264 Fix synchronizer tests
  tests_scripts/helm/synchronizer.py
Labels: bug_fix, Review effort [1-5]: 1

#261 Revert "NP tests - remove backend validation"
  tests_scripts/helm/network_policy.py
Labels: enhancement, Review effort [1-5]: 2

#266 remove hardcoded synchronizer tag
  tests_scripts/helm/synchronizer.py
Labels: enhancement, Review effort [1-5]: 1

#267 add get env func with log
  tests_scripts/users_notifications/alert_notifications.py
Labels: enhancement, Review effort [1-5]: 2, Possible security concern

#268 fix inconsistent time format
  tests_scripts/users_notifications/alert_notifications.py
Labels: bug_fix, Review effort [1-5]: 2

#269 Remove deprecated tests names
  system_test_mapping.json
Labels: enhancement, Review effort [1-5]: 2

#270 Add config repo check in repo scan tests
  tests_scripts/kubescape/scan.py
Labels: enhancement, Tests, Review effort [1-5]: 2

#272 Adding vuln_scan_cve_exceptions to mapping file
  system_test_mapping.json
Labels: enhancement, Review effort [1-5]: 1

#271 fail the test if we failed to delete repo
  tests_scripts/kubescape/scan.py
Labels: Tests, bug_fix, Review effort [1-5]: 1

#273 enable slack and teams tests in config-service and uns
  system_test_mapping.json
Labels: enhancement, Review effort [1-5]: 1
