Repository armosec/system-tests, pull requests merged in 2024-09, with the labels that each got.

#455 set podScanGuardTime to 1m to fix tests
  tests_scripts/helm/base_helm.py
Labels: Tests, bug_fix, Review effort [1-5]: 1

#456 lower podScanGuardTime override to avoid timeouts
  tests_scripts/helm/base_helm.py
Labels: enhancement, bug_fix, Review effort [1-5]: 1

#458 chore: Update expected values for security risks
  configurations/scenarios_expected_values/attack-chain-5_security-risks-uv-category.json
  configurations/scenarios_expected_values/attack-chain-5_security-risks-uv-namespace.json
  configurations/scenarios_expected_values/attack-chain-5_security-risks-uv-securityriskname.json
  configurations/scenarios_expected_values/attack-chain-5_security-risks-uv-severity.json
Labels: enhancement, Review effort [1-5]: 1

#459 chore: Add count parameter to summarize_uniquevalues function
  systest_utils/scenarios_manager.py
Labels: enhancement, Review effort [1-5]: 2

#460 chore: Update vulnerability notes with additional resources
  configurations/expected-result/V2_VIEWS/kev_vulan.json
Labels: documentation, Review effort [1-5]: 1

#457 fix ac_with_exceptions
  infrastructure/backend_api.py
  systest_utils/scenarios_manager.py
  tests_scripts/helm/ks_microservice.py
Labels: enhancement, Tests, Review effort [1-5]: 3

#461 disable node agent in ks tests
  infrastructure/helm_wrapper.py
  tests_scripts/helm/ks_microservice.py
  tests_scripts/kubescape/base_kubescape.py
Labels: enhancement, Tests, Review effort [1-5]: 2

#462 reduce resources
  configurations/scenarios-test-env/attack-chain-1-1/03-wordpress.yaml
  configurations/scenarios-test-env/attack-chain-1-2/03-wordpress.yaml
  configurations/scenarios-test-env/attack-chain-2/03-wordpress.yaml
  configurations/scenarios-test-env/attack-chain-3/03-wordpress.yaml
  configurations/scenarios-test-env/attack-chain-4/03-wordpress.yaml
  configurations/scenarios-test-env/attack-chain-5/02-wordpress.yaml
  configurations/scenarios-test-env/attack-chain-6/02-wordpress.yaml
  configurations/scenarios-test-env/attack-chain-7/02-wordpress.yaml
  configurations/scenarios-test-env/attack-chain-9/02-service-unauthnticated.yaml
  infrastructure/helm_wrapper.py
Labels: enhancement, Review effort [1-5]: 2

#463 fix version
  tests_scripts/helm/ks_microservice.py
Labels: bug_fix, Review effort [1-5]: 1

#464 fix check
  tests_scripts/helm/jira_integration.py
Labels: bug_fix, Review effort [1-5]: 2

#465 disable test in prod
  tests_scripts/helm/ks_microservice.py
Labels: Tests, Review effort [1-5]: 2

#466 temp disable tests in prod
  tests_scripts/helm/jira_integration.py
  tests_scripts/helm/synchronizer.py
Labels: Tests, Review effort [1-5]: 2

#467 Temp disable
  tests_scripts/helm/jira_integration.py
Labels: Tests, Review effort [1-5]: 2

#468 fix test
  test_driver.py
  tests_scripts/kubernetes/base_k8s.py
  tests_scripts/runtime/incidents.py
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#471 Refactor security risks tests to create new tenant for exception dele…
  configurations/system/tests_cases/security_risks_tests.py
  systest_utils/scenarios_manager.py
  tests_scripts/helm/ks_microservice.py
Labels: enhancement, Tests, Review effort [1-5]: 2
