Repository armosec/system-tests, pull requests merged in 2024-08, with the labels that each got.

#420 Sub 5140
  configurations/ks-exceptions/exclude-control-sa-resourceID-regex.json
  configurations/ks-exceptions/exclude-control-with-regex.json
  configurations/system/tests_cases/kubescape_tests.py
  configurations/system/tests_cases/vuln_scan_tests.py
  system_test_mapping.json
  tests_scripts/helm/vuln_scan.py
Labels: enhancement, Tests, Review effort [1-5]: 3

#436 adding kdr slack and teams tests
  configurations/system/tests_cases/runtime_tests.py
  system_test_mapping.json
  systest_utils/statics.py
  tests_scripts/helm/base_helm.py
  tests_scripts/runtime/alerts.py
  tests_scripts/runtime/incidents.py
  tests_scripts/runtime/policies.py
  tests_scripts/users_notifications/alert_notifications.py
Labels: enhancement, Tests, Review effort [1-5]: 3

#437 chore: Add incidents verification in runtime alerts test
  tests_scripts/runtime/alerts.py
Labels: enhancement, Tests, Review effort [1-5]: 2

#438 chore: Remove logging statement in IncidentsAlerts class
  tests_scripts/runtime/alerts.py
  tests_scripts/runtime/policies.py
Labels: enhancement, Review effort [1-5]: 1

#439 chore: Add users-notification-service to system test mapping
  system_test_mapping.json
Labels: enhancement, Review effort [1-5]: 1

#440 chore: Update system test mapping to include event-ingester-service-d…
  system_test_mapping.json
Labels: enhancement, Review effort [1-5]: 1

#442 chore: Update incident name in IncidentsAlerts class
  tests_scripts/runtime/alerts.py
Labels: enhancement, Review effort [1-5]: 1

#443 Revert "chore: Update incident name in IncidentsAlerts class"
  tests_scripts/runtime/alerts.py
Labels: Bug fix, Review effort [1-5]: 1

#444 chore: Update expectedJiraSchema.json to reflect changes in Jira schema
  configurations/expected-result/integrations/expectedJiraSchema.json
Labels: enhancement, Review effort [1-5]: 1

#445 chore: Update networkPolicyStatus in attack-chain-5_security-risks-re…
  configurations/scenarios_expected_values/attack-chain-5_security-risks-resources_sidebar_R0007.json
Labels: enhancement, Review effort [1-5]: 1

#446 update expected values for ac_9 test
  configurations/scenarios_expected_values/attack-chain-9.json
Labels: enhancement, Review effort [1-5]: 2

#447 chore: Update ac_9 system test
  configurations/system/tests_cases/ks_microservice_test.py
  systest_utils/statics.py
  tests_scripts/users_notifications/alert_notifications.py
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#448 chore: Disable waiting for aggregation to end in BaseTest
  tests_scripts/base_test.py
Labels: enhancement, Review effort [1-5]: 1

#449 updating ac tests
  configurations/system/tests_cases/ks_microservice_test.py
  readme.md
  system_test_mapping.json
Labels: documentation, enhancement, Review effort [1-5]: 2

#451 chore: Add delay before validating security risks trends in ks_micros…
  tests_scripts/helm/ks_microservice.py
Labels: enhancement, Review effort [1-5]: 1

#450 migrate network tests to NetworkNeighborhoods
  configurations/kubescape-crds/supported/networkneighborhood.yaml
  configurations/network-policy/expected-network-neighborhood/busybox-known-server.json
  configurations/network-policy/expected-network-neighborhood/busybox.json
  configurations/network-policy/expected-network-neighborhood/deployment-mariadb-basic.json
  configurations/network-policy/expected-network-neighborhood/deployment-mariadb.json
  configurations/network-policy/expected-network-neighborhood/deployment-nginx-basic.json
  configurations/network-policy/expected-network-neighborhood/deployment-nginx.json
  configurations/network-policy/expected-network-neighborhood/deployment-wikijs-basic.json
  configurations/network-policy/expected-network-neighborhood/deployment-wikijs.json
  configurations/network-policy/expected-network-neighbors/busybox-known-server.json
  configurations/network-policy/expected-network-neighbors/busybox.json
  configurations/network-policy/expected-network-neighbors/deployment-nginx-basic.json
  configurations/network-policy/expected-network-neighbors/deployment-wikijs-basic.json
  configurations/network-policy/expected-network-neighbors/deployment-wikijs.json
  configurations/system/tests_cases/network_policy_tests.py
  infrastructure/kubectl_wrapper.py
  system_test_mapping.json
  systest_utils/statics.py
  tests_scripts/helm/base_network_policy.py
  tests_scripts/helm/network_policy.py
  tests_scripts/helm/synchronizer.py
  tests_scripts/kubernetes/base_k8s.py
Labels: enhancement, Tests, Review effort [1-5]: 3

#452 chore: Update security risk name in nginx_security-risks-list.json
  configurations/scenarios_expected_values/nginx_security-risks-list.json
Labels: enhancement, Review effort [1-5]: 1

#453 pin version of deepdiff to avoid regression
  requirements.txt
Labels: Review effort [1-5]: 1, dependencies
