Repository armosec/system-tests, pull requests merged in 2024-11, with the labels that each got.

#477 change control to C-0057
  configurations/ks-custom-fw/system-test-framework-high-comp.json
Labels: Review effort [1-5]: 1

#478 print value temporary
  tests_scripts/users_notifications/alert_notifications.py
Labels: Review effort [1-5]: 1

#479 print value temporary
  tests_scripts/users_notifications/alert_notifications.py
Labels: Review effort [1-5]: 2

#482 change order of apply security risks scenario after helm chart is installed, Increase timeout of waiting for incidents
  tests_scripts/helm/ks_microservice.py
  tests_scripts/runtime/alerts.py
Labels: Review effort [1-5]: 2

#483 scan all controls fw instead of security fw
  systest_utils/scenarios_manager.py
Labels: Review effort [1-5]: 1

#484 Fix sr tests
  tests_scripts/helm/network_policy.py
Labels: Review effort [1-5]: 1

#488 skip tests
  tests_scripts/helm/ks_microservice.py
Labels: Review effort [1-5]: 1

#489 removed skip tests
  tests_scripts/helm/ks_microservice.py
Labels: Review effort [1-5]: 1

#490 disable submit for networkpolicy tests
  configurations/system/tests_cases/network_policy_tests.py
Labels: Review effort [1-5]: 1

#492 fix: correct spelling of 'compliance' in alert notification check
  tests_scripts/users_notifications/alert_notifications.py
Labels: Review effort [1-5]: 1

#493 update seccomp profile for alpine
  configurations/k8s_workloads/seccomp/seccomp-alpine-optimized.yaml
Labels: Review effort [1-5]: 3
