Repository armosec/system-tests, pull requests merged in 2024-04, with the labels that each got.

#297 hardcoded kubescape cli version in test (temporary)
  tests_scripts/kubescape/scan.py
Labels: enhancement

#298 build ks using go build
  tests_scripts/kubescape/base_kubescape.py
Labels: enhancement, Review effort [1-5]: 2

#299 temporary disable test
  tests_scripts/kubescape/scan.py
Labels: enhancement, Tests, Review effort [1-5]: 2

#300 enable test
  tests_scripts/kubescape/scan.py
Labels: Tests, Review effort [1-5]: 1

#301 upd wl ex
  configurations/expected-result/V2_VIEWS/wl_details.json
  configurations/expected-result/V2_VIEWS/wl_filtered.json
Labels: enhancement, Review effort [1-5]: 1

#302 Ignore new resource hash field in vuln workload
  tests_scripts/helm/vuln_scan.py
Labels: enhancement, Review effort [1-5]: 2

#303 Add default timeout value if not provided
  infrastructure/backend_api.py
Labels: enhancement, Review effort [1-5]: 2

#305 Update expected cve id
  configurations/expected-result/V2_VIEWS/cve_details.json
Labels: enhancement, Review effort [1-5]: 1

#306 Ignore comp version
  tests_scripts/helm/vuln_scan.py
Labels: enhancement, Review effort [1-5]: 1

#304 print highlights when we time out on smart remediation
  tests_scripts/helm/smart_remediation.py
  tests_scripts/helm/synchronizer.py
Labels: enhancement, Tests, Review effort [1-5]: 2

#308 v2-views: Use fixed version of httpd instead of latest
  configurations/expected-result/V2_VIEWS/cve_details.json
  configurations/expected-result/V2_VIEWS/image_details.json
  configurations/expected-result/V2_VIEWS/wl_details.json
  configurations/expected-result/V2_VIEWS/wl_filtered.json
  configurations/k8s_workloads/deployments/viewsv2/httpdproxy.yaml
Labels: enhancement, Review effort [1-5]: 2

#309 fix httpd no longer have critical cves
  configurations/notifications/deployments/http/apache-http.yaml
  configurations/notifications/slack-alert-channel.json
  configurations/notifications/teams-alert-channel.json
  tests_scripts/users_notifications/alert_notifications.py
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#310 Update target repositories in system_test_mapping.json
  system_test_mapping.json
Labels: enhancement, Review effort [1-5]: 1

#311 Scenarios manager
  systest_utils/scenarios_manager.py
  tests_scripts/helm/ks_microservice.py
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#315 Update psycopg2-binary version in requirements.txt
  requirements.txt
Labels: enhancement, Review effort [1-5]: 1

#316 Sr tests
  configurations/scenarios_expected_values/attack-chain-5_security-risks-resources_sidebar_R0002.json
  configurations/scenarios_expected_values/attack-chain-5_security-risks-resources_sidebar_R0035.json
  configurations/scenarios_expected_values/attack-chain-5_security-risks-uv-category.json
  configurations/scenarios_expected_values/attack-chain-5_security-risks-uv-namespace.json
  configurations/scenarios_expected_values/attack-chain-5_security-risks-uv-securityriskname.json
  configurations/scenarios_expected_values/attack-chain-5_security-risks-uv-severity.json
  infrastructure/backend_api.py
  readme.md
  system_test_mapping.json
  systest_utils/scenarios_manager.py
  tests_scripts/helm/ks_microservice.py
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#317 Update severity values in attack-chain-5_security-risks-uv-severity.json
  configurations/scenarios_expected_values/attack-chain-5_security-risks-resources_sidebar_R0035.json
  configurations/scenarios_expected_values/attack-chain-5_security-risks-uv-severity.json
  systest_utils/scenarios_manager.py
  tests_scripts/helm/ks_microservice.py
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#319 Update target repositories in system_test_mapping.json
  system_test_mapping.json
Labels: enhancement, Review effort [1-5]: 1

#321 Fix security risks tests and update target repositories
  configurations/system/tests_cases/security_risks_tests.py
  system_test_mapping.json
  tests_scripts/helm/ks_microservice.py
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#322 Fix/sync checks
  tests_scripts/helm/synchronizer.py
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#323 Sr tests
  configurations/scenarios-test-env/attack-chain-5/delete_deployments
  configurations/scenarios-test-env/attack-chain-5/fix_control
  configurations/scenarios-test-env/attack-chain-5/fix_image
  configurations/scenarios-test-env/deploy_scenario
  configurations/system/tests_cases/security_risks_tests.py
  infrastructure/backend_api.py
  systest_utils/scenarios_manager.py
  tests_scripts/base_test.py
  tests_scripts/helm/base_helm.py
  tests_scripts/helm/ks_microservice.py
  tests_scripts/kubescape/base_kubescape.py
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#324 Sr tests
  configurations/scenarios_expected_values/attack-chain-5_security-risks-resources_sidebar_R0005.json
  configurations/system/tests_cases/security_risks_tests.py
  readme.md
  system_test_mapping.json
  systest_utils/scenarios_manager.py
  tests_scripts/helm/ks_microservice.py
Labels: enhancement, Tests, Review effort [1-5]: 3

#326 Scan status test
  configurations/system/tests_cases/security_risks_tests.py
  infrastructure/backend_api.py
  system_test_mapping.json
  systest_utils/scenarios_manager.py
  tests_scripts/helm/ks_microservice.py
Labels: enhancement, Tests, Review effort [1-5]: 3

#325 Add security risk notification to Slack and Teams alert channels, and update delay for notifications service
  configurations/notifications/slack-alert-channel.json
  configurations/notifications/teams-alert-channel.json
  tests_scripts/users_notifications/alert_notifications.py
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#327 specify security_risks_ids in sr_ac_scan_status
  configurations/system/tests_cases/security_risks_tests.py
Labels: enhancement

#328 enable sr_ac_scan_status test in repos
  system_test_mapping.json
Labels: enhancement, Review effort [1-5]: 1

#329 Sr with exceptions
  configurations/scenarios_expected_values/attack-chain-5_security-risks-exceptions-edit-response.json
  configurations/scenarios_expected_values/attack-chain-5_security-risks-exceptions-list.json
  configurations/system/tests_cases/security_risks_tests.py
  infrastructure/backend_api.py
  readme.md
  system_test_mapping.json
  systest_utils/scenarios_manager.py
  tests_scripts/helm/ks_microservice.py
Labels: enhancement, bug_fix

#331 Fix bug in SecurityRisksScenarioManager exception handling logic
  systest_utils/scenarios_manager.py
Labels: bug_fix, Review effort [1-5]: 2

#332 Update NOTIFICATIONS_SVC_DELAY to 7 minutes in alert_notifications.py
  tests_scripts/users_notifications/alert_notifications.py
Labels: enhancement, Review effort [1-5]: 1

#333 disable slack+teams tests to run on prod util we overcome the too man…
  system_test_mapping.json
Labels: Tests, Review effort [1-5]: 1

#335 Cli operator test
  configurations/system/tests_cases/ks_microservice_test.py
  configurations/system/tests_cases/relevant_vuln_scanning_tests.py
Labels: enhancement, Tests

#336 fixed test
  tests_scripts/kubescape/base_kubescape.py
Labels: enhancement, Review effort [1-5]: 2
