Repository armosec/system-tests, pull requests merged in 2024-01, with the labels that each got.

#216 Rename filtered sboms
  tests_scripts/helm/base_vulnerability_scanning.py
Labels: enhancement

#217 add sleep before test message check
  tests_scripts/users_notifications/alert_notifications.py
Labels: bug_fix

#218 OPS-601 Force System Test to be added to system_test_mapping.json
  .github/workflows/validate_json.yaml
  systest-cli.py
Labels: enhancement, Tests

#219 Updated system_test_mapping.json
  system_test_mapping.json
Labels: enhancement

#227 timeout fixes
  tests_scripts/helm/vulnerability_scanning.py
Labels: Bug fix

#229 skip test_results_details_against_results_sum_summary
  tests_scripts/helm/base_vulnerability_scanning.py
Labels: enhancement

#230 Remove unused methods and clean up code
  infrastructure/backend_api.py
  tests_scripts/dockerize/base_dockerize_test.py
  tests_scripts/helm/ks_microservice.py
  tests_scripts/kubescape/base_kubescape.py
Labels: enhancement

#232 Network policies tests
  configurations/system/tests_cases/network_policy_tests.py
  infrastructure/backend_api.py
  system_test_mapping.json
  tests_scripts/helm/base_network_policy.py
  tests_scripts/helm/network_policy.py
Labels: Tests

#233 improvements
  tests_scripts/kubescape/base_kubescape.py
Labels: enhancement

#235 Add network policy targets and descriptions
  system_test_mapping.json
Labels: enhancement

#236 Update sleep duration in network_policy.py
  tests_scripts/helm/base_network_policy.py
  tests_scripts/helm/network_policy.py
Labels: enhancement

#239 Add remove_cluster_from_backend parameter to BaseKubescape constructor
  tests_scripts/kubescape/base_kubescape.py
Labels: enhancement

#240 Removed functions
  tests_scripts/helm/network_policy.py
  tests_scripts/kubescape/scan.py
Labels: Review effort [1-5]: 1

#241 Fix np tests
  system_test_mapping.json
  tests_scripts/helm/base_helm.py
  tests_scripts/helm/base_network_policy.py
  tests_scripts/helm/network_policy.py
Labels: Review effort [1-5]: 3

#242 Update target repositories in system_test_mapping.json
  system_test_mapping.json
Labels: enhancement

#243 Commented out unnecessary code in display_armo_system_logs method
  tests_scripts/helm/base_helm.py
Labels: enhancement, Review effort [1-5]: 1

#245 Update ac and vuln test names
  configurations/system/tests.py
  configurations/system/tests_cases/ks_microservice_test.py
  configurations/system/tests_cases/ks_vuln_scan_tests.py
  configurations/system/tests_cases/relevant_vuln_scanning_tests.py
  configurations/system/tests_cases/vuln_scan_tests.py
  jenkins_files/Jenkinsfile-helm-ks-be-test.groovy
  jenkins_files/Jenkinsfile-helm-ks-be.groovy
  jenkins_files/Jenkinsfile_helm_chart.groovy
  jenkins_files/Jenkinsfile_helm_chart_on_going_features.groovy
  jenkins_files/Jenkinsfile_payment.groovy
  jenkins_files/Jenkinsfile_relevancy.groovy
  readme.md
  system_test_mapping.json
  systest_utils/statics.py
  tests_scripts/helm/base_vuln_scan.py
  tests_scripts/helm/ks_vuln_scan.py
  tests_scripts/helm/relevant_cve.py
  tests_scripts/helm/vuln_scan.py
Labels: enhancement, Review effort [1-5]: 3

#246 fix folder name
  configurations/vuln_scan/expected_results/layers.json
  configurations/vuln_scan/expected_results/nginx-new-image.json
  configurations/vuln_scan/expected_results/wikijs.json
Labels: enhancement
