Repository armosec/system-tests, pull requests merged in 2025-03, with the labels that each got.

#618 Increase sleep interval in wait_for_report method for incident verifi…
  tests_scripts/runtime/alerts.py
Labels: Review effort 1/5

#619 Enhance Jira ticket validation by including cluster context and impro…
  tests_scripts/workflows/jira_workflows.py
  tests_scripts/workflows/utils.py
Labels: Review effort 2/5

#623 Update system test mapping to skip tests on staging environment
  system_test_mapping.json
Labels: Review effort 1/5

#624 Update system test mapping to adjust skip_on_environment settings
  system_test_mapping.json
  tests_scripts/workflows/jira_workflows.py
Labels: Review effort 1/5

#625 Remove unused return statement in WorkflowsJiraNotifications method
  tests_scripts/workflows/jira_workflows.py
Labels: Review effort 1/5

#626 Enhance JIRA API request headers with authorization and content type
  tests_scripts/workflows/utils.py
Labels: Review effort 2/5

#627 add cspm test
  .gitignore
  configurations/system/tests_cases/accounts_tests.py
  infrastructure/aws.py
  infrastructure/backend_api.py
  requirements.txt
  tests_scripts/accounts/accounts.py
  tests_scripts/accounts/connect.py
  tests_scripts/accounts/cspm_test_models.py
  tests_scripts/helm/jira_integration.py
  tests_scripts/workflows/jira_workflows.py
Labels: Review effort 4/5

#629 enlrage timeout
  tests_scripts/accounts/connect.py
Labels: Review effort 1/5

#630 skipping test
  tests_scripts/accounts/connect.py
Labels: Review effort 1/5

#628 refactor webhook handling to use teams-specific methods and endpoints
  infrastructure/backend_api.py
  system_test_mapping.json
  systest_utils/statics.py
  tests_scripts/runtime/policies.py
  tests_scripts/workflows/conf_workflows.py
  tests_scripts/workflows/teams_workflows.py
Labels: Review effort 3/5

#632 add skip_apis_validation flag to CloudConnect for conditional API val…
  tests_scripts/accounts/connect.py
Labels: Review effort 2/5

#633 add conditional check for skip_apis_validation in CloudConnect discon…
  tests_scripts/accounts/connect.py
Labels: Review effort 1/5

#634 enable
  tests_scripts/accounts/connect.py
Labels: Review effort 1/5
