Repository armosec/system-tests, pull requests merged in 2025-08, with the labels that each got.

#693 fix network_policy_pod_restarted expected result for new node-agent
  configurations/network-policy/expected-generated-network-policy/deployment-mariadb-basic.json
Labels: Review effort 1/5

#698 fix expected NN status in network_policy_pod_restarted
  configurations/network-policy/expected-network-neighborhood/deployment-wikijs.json
Labels: Review effort 1/5

#700 Revert "fix expected NN status in network_policy_pod_restarted"
  configurations/network-policy/expected-network-neighborhood/deployment-wikijs.json
Labels: Review effort 1/5

#701 fix network_policy_pod_restarted by finishing learning
  configurations/system/tests_cases/network_policy_tests.py
  systest_utils/statics.py
  tests_scripts/helm/network_policy.py
Labels: Review effort 2/5

#702 Update CSPM API endpoint and modify get_cspm_link method to use POST with JSON body
  infrastructure/backend_api.py
Labels: Review effort 2/5

#704 Refactor get_cspm_link method in Accounts class to use string "true" …
  tests_scripts/accounts/accounts.py
Labels: Review effort 1/5

#706 Refactor Jira ticket retrieval in get_tickets_from_jira_channel. Adde…
  tests_scripts/workflows/jira_workflows.py
  tests_scripts/workflows/utils.py
Labels: Review effort 2/5

#707 Cspm org
  infrastructure/backend_api.py
  tests_scripts/accounts/accounts.py
  tests_scripts/accounts/connect_org.py
Labels: Review effort 3/5

#708 ka
  tests_scripts/accounts/connect_org.py
Labels: Review effort 1/5

#709 fix systets
  tests_scripts/accounts/accounts.py
Labels: Review effort 2/5

#710 fix test
  tests_scripts/accounts/connect.py
Labels: Review effort 1/5

#713 temporarily disable teams
  tests_scripts/workflows/teams_workflows.py
Labels: Review effort 1/5
