Repository armosec/system-tests, pull requests merged in 2025-09, with the labels that each got.

#720 fix backends urls
  configurations/system/backends.py
Labels: Review effort 1/5

#721 attempting to fix network policy tests
  configurations/network-policy/expected-generated-network-policy/deployment-mariadb-basic.json
  configurations/network-policy/expected-generated-network-policy/deployment-mariadb.json
  configurations/network-policy/expected-generated-network-policy/deployment-nginx-basic.json
  configurations/network-policy/expected-generated-network-policy/deployment-nginx.json
  configurations/network-policy/expected-generated-network-policy/deployment-wikijs-basic.json
  configurations/network-policy/expected-generated-network-policy/deployment-wikijs.json
  configurations/network-policy/expected-network-neighborhood/deployment-mariadb.json
  configurations/network-policy/expected-network-neighborhood/deployment-nginx.json
  configurations/network-policy/expected-network-neighborhood/deployment-wikijs.json
  configurations/system/tests_cases/network_policy_tests.py
  tests_scripts/helm/base_network_policy.py
  tests_scripts/helm/network_policy.py
Labels: Review effort 2/5

#725 Add 'vulnerability-scanner' to target repositories in system_test_map…
  system_test_mapping.json
Labels: Review effort 1/5

#728 Add cleanup logic to delete CSPM vulnerability scan stack in CloudVul…
  infrastructure/aws.py
  tests_scripts/accounts/vulnscan.py
Labels: Review effort 1/5

#729 add return success
  tests_scripts/accounts/connect_org.py
Labels: Review effort 1/5

#733 add fix cspm scan now
  infrastructure/backend_api.py
  tests_scripts/accounts/accounts.py
Labels: Review effort 2/5

#735 ka
  tests_scripts/accounts/connect.py
Labels: Review effort 1/5

#739 Revert "fix relevancy_fix_vuln expected output"
  configurations/expected-result/CVEs/redis-fixed.json
  configurations/expected-result/CVEs/redis.json
  configurations/expected-result/SBOM/redis.json
  configurations/expected-result/filteredCVEs/redis-fixed.json
  configurations/expected-result/filteredCVEs/redis.json
  configurations/helm-proxy/httpd.conf
  configurations/helm-proxy/san_scr.cnf
Labels: Review effort 1/5

#731 Connection test
  infrastructure/aws.py
  infrastructure/backend_api.py
  requirements.txt
  tests_scripts/accounts/accounts.py
  tests_scripts/accounts/connect.py
  tests_scripts/accounts/connect_org.py
  tests_scripts/accounts/cspm_test_models.py
  tests_scripts/accounts/vulnscan.py
Labels: Possible security concern, Review effort 4/5

#742 Connection test
  tests_scripts/accounts/accounts.py
  tests_scripts/accounts/connect.py
  tests_scripts/accounts/connect_org.py
Labels: Review effort 2/5
