Repository armosec/system-tests, pull requests merged in 2025-01, with the labels that each got.

#550 Refactor cluster state logging to join output lines for better readab…
  tests_scripts/kubernetes/base_k8s.py
  tests_scripts/workflows/teams_workflows.py
Labels: Review effort [1-5]: 1, Possible security concern

#551 Fix teams
  tests_scripts/workflows/teams_workflows.py
  tests_scripts/workflows/utils.py
Labels: Review effort [1-5]: 2

#552 jira_integration - added retry mechnism in case of hitting rate limit
  tests_scripts/helm/jira_integration.py
  tests_scripts/kubernetes/base_k8s.py
Labels: Review effort [1-5]: 1

#553 Fix verify pods and jira rate limit handling
  infrastructure/backend_api.py
  tests_scripts/helm/jira_integration.py
  tests_scripts/kubernetes/base_k8s.py
Labels: Review effort [1-5]: 2

#554 Remove logging of not running pods details in BaseK8S class for clean…
  tests_scripts/kubernetes/base_k8s.py
Labels: Review effort [1-5]: 1

#546 Accounts - cloud and posture
  configurations/system/tests.py
  configurations/system/tests_cases/accounts_tests.py
  infrastructure/backend_api.py
  system_test_mapping.json
  tests_scripts/accounts/accounts.py
Labels: Review effort [1-5]: 4

#557 updating system tests mapping
  system_test_mapping.json
Labels: Review effort [1-5]: 2

#558 increase the timeout time
  infrastructure/backend_api.py
Labels: Review effort [1-5]: 1

#559 add authorization header
  infrastructure/backend_api.py
Labels: Review effort [1-5]: 2

#560 Authorization header
  infrastructure/backend_api.py
Labels: Review effort [1-5]: 1

#561 hardcoded helm chart version
  configurations/system/tests_cases/vuln_scan_tests.py
  tests_scripts/helm/vuln_scan.py
Labels: Review effort [1-5]: 2

#562 Refactor workflow validation to improve query efficiency and ensure s…
  tests_scripts/kubernetes/base_k8s.py
  tests_scripts/workflows/jira_workflows.py
Labels: Review effort [1-5]: 2

#563 Add return statement for workflow GUID in Slack notifications assertion
  tests_scripts/workflows/slack_workflows.py
Labels: Review effort [1-5]: 1

#564 remove irrelevant registry scanning tests
  configurations/system/tests_cases/vuln_scan_tests.py
  tests_scripts/helm/vuln_scan.py
Labels: Review effort [1-5]: 2

#565 Add system test mappings for various relevancy scenarios in JSON conf…
  system_test_mapping.json
Labels: Review effort [1-5]: 2

#569 Disable vulnerability and relevancy scans in Helm configurations acro…
  tests_scripts/helm/base_network_policy.py
  tests_scripts/helm/ks_microservice.py
  tests_scripts/helm/network_policy.py
  tests_scripts/helm/smart_remediation.py
  tests_scripts/helm/vuln_scan.py
Labels: Review effort [1-5]: 2

#571 Update target repositories in system_test_mapping and modify return s…
  system_test_mapping.json
  tests_scripts/helm/vuln_scan.py
Labels: Review effort [1-5]: 1

#572 Add new entries for relevancy disabled installations and storage in s…
  system_test_mapping.json
Labels: Review effort [1-5]: 1

#573 remove old registry scan tests
  configurations/system/tests_cases/registry_tests.py
  configurations/system/tests_cases/vuln_scan_tests.py
  infrastructure/backend_api.py
  infrastructure/kubectl_wrapper.py
  jenkins_files/Jenkinsfile-helm-ks-be-test.groovy
  jenkins_files/Jenkinsfile-helm-ks-be.groovy
  jenkins_files/Jenkinsfile_helm_chart.groovy
  jenkins_files/Jenkinsfile_helm_chart_on_going_features.groovy
  jenkins_files/Jenkinsfile_kubescape.groovy
  jenkins_files/Jenkinsfile_payment.groovy
  jenkins_files/Jenkinsfile_relevancy.groovy
  jenkins_files/Jenkinsfile_single_test.groovy
  readme.md
  system_test_mapping.json
  tests_scripts/helm/base_vuln_scan.py
  tests_scripts/helm/vuln_scan.py
Labels: Review effort [1-5]: 3

#574 remove unused imports from vulnerability scanning test files
  configurations/system/tests_cases/relevant_vuln_scanning_tests.py
  configurations/system/tests_cases/vuln_scan_tests.py
Labels: Review effort [1-5]: 1

#575 add collabGUID to update config func
  tests_scripts/helm/jira_integration.py
Labels: Review effort [1-5]: 1

#576 remove redundant parameter from vulnerability retrieval in Jira workf…
  tests_scripts/workflows/jira_workflows.py
Labels: Review effort [1-5]: 1

#578 return success status in RegistryChecker start method
  tests_scripts/registry/registry_connectors.py
Labels: Review effort [1-5]: 2

#579 Revert "Merge pull request #578 from armosec/temp_remove_tst"
  tests_scripts/registry/registry_connectors.py
Labels: Review effort [1-5]: 1

#581 restore missing tests from mapping used by Kubescape
  system_test_mapping.json
Labels: Review effort [1-5]: 2

#582 Add namespace argument support to control scripts and update attack c…
  configurations/scenarios-test-env/alpine/fix_control
  configurations/scenarios-test-env/alpine/fix_image
  configurations/scenarios-test-env/attack-chain-8/fix_control
  configurations/scenarios-test-env/attack-chain-9/02-service-unauthnticated.yaml
  configurations/scenarios-test-env/attack-chain-9/fix_control
  configurations/system/tests_cases/ks_microservice_test.py
  infrastructure/backend_api.py
  readme.md
  system_test_mapping.json
  systest_utils/scenarios_manager.py
  tests_scripts/helm/ks_microservice.py
Labels: Review effort [1-5]: 4

#584 Refactor scenario validation logic to improve clarity and adjust time…
  systest_utils/scenarios_manager.py
Labels: Review effort [1-5]: 2

#585 Remove deprecated attack chain scenarios and update related documenta…
  configurations/system/tests_cases/ks_microservice_test.py
  readme.md
  system_test_mapping.json
  tests_scripts/helm/ks_microservice.py
Labels: Review effort [1-5]: 2

#587 Refactor security risk tests and update storage class references in c…
  configurations/scenarios-test-env/attack-chain-5/01-mysql.yaml
  configurations/system/tests_cases/security_risks_tests.py
  system_test_mapping.json
  systest_utils/scenarios_manager.py
  tests_scripts/helm/ks_microservice.py
  tests_scripts/kubernetes/base_k8s.py
Labels: Review effort [1-5]: 4

#588 Sr
  configurations/system/tests_cases/security_risks_tests.py
Labels: Review effort [1-5]: 1

#590 skip google registry check
  tests_scripts/registry/registry_connectors.py
Labels: Review effort [1-5]: 1

#591 Improvetests
  tests_scripts/helm/ks_microservice.py
Labels: Review effort [1-5]: 1

#592 add sleep to avoid missing syncronizer resource in pg
  tests_scripts/registry/registry_connectors.py
Labels: Review effort [1-5]: 1

#593 refactor: streamline pod verification process by removing unnecessary…
  tests_scripts/helm/relevant_cve.py
Labels: Review effort [1-5]: 2

#594 fix the validate workflow func
  tests_scripts/workflows/teams_workflows.py
Labels: Review effort [1-5]: 1

#596 Accounts tests
  configurations/system/tests_cases/accounts_tests.py
  infrastructure/aws.py
  infrastructure/backend_api.py
  system_test_mapping.json
  tests_scripts/accounts/accounts.py
  tests_scripts/accounts/clusters.py
  tests_scripts/accounts/cspm.py
Labels: Review effort [1-5]: 4

#598 skip cspm
  tests_scripts/accounts/cspm.py
Labels: Review effort [1-5]: 2

#599 return cspm tests
  tests_scripts/accounts/cspm.py
Labels: Review effort [1-5]: 1

#601 Update assertion in CSPM test to check for 'guid' in response
  tests_scripts/accounts/cspm.py
Labels: Review effort [1-5]: 1
