Repository armosec/system-tests, pull requests merged in 2025-04, with the labels that each got.

#635 fix unique values
  configurations/expected-result/kdr/runtime_policies_unique_values.json
  tests_scripts/runtime/policies.py
Labels: Review effort 1/5

#637 add simulation for unexpected process incidents and update capabilities
  tests_scripts/runtime/incidents.py
Labels: Review effort 2/5

#636 fixed tests
  tests_scripts/runtime/policies.py
Labels: Review effort 1/5

#638 feat: add incident response functionality and webhook alert support
  configurations/system/tests_cases/runtime_tests.py
  infrastructure/backend_api.py
  system_test_mapping.json
  systest_utils/statics.py
  tests_scripts/runtime/incidents.py
  tests_scripts/runtime/policies.py
  tests_scripts/runtime/response.py
Labels: Review effort 3/5

#641 feat: add support for dynamic test namespace creation in incident res…
  configurations/system/tests_cases/runtime_tests.py
  infrastructure/backend_api.py
  system_test_mapping.json
  tests_scripts/helm/base_helm.py
  tests_scripts/runtime/incidents.py
  tests_scripts/runtime/response.py
Labels: Review effort 2/5

#643 fix relevancy_large_image results
  configurations/expected-result/SBOM/redis_incomplete.json
Labels: Review effort 1/5

#645 fix results for relevantCVEs test
  configurations/expected-result/filteredCVEs/mariadb.json
Labels: Review effort 1/5

#648 refactor: comment out cleanup method in IncidentResponse class
  tests_scripts/runtime/response.py
Labels: Review effort 1/5

#650 fix: update notes for HTTP/2 Rapid Reset Vulnerability details
  configurations/expected-result/V2_VIEWS/kev_vulan.json
Labels: Review effort 1/5

#652 Disable SBOM
  configurations/system/tests_cases/relevant_vuln_scanning_tests.py
  tests_scripts/helm/jira_integration.py
  tests_scripts/helm/ks_microservice.py
  tests_scripts/helm/vuln_scan.py
  tests_scripts/workflows/jira_workflows.py
Labels: Review effort 2/5

#653 ka'
  tests_scripts/accounts/connect.py
Labels: Review effort 1/5

#654 SBOM test
  configurations/system/tests_cases/ks_microservice_test.py
  infrastructure/backend_api.py
  system_test_mapping.json
  systest_utils/statics.py
  tests_scripts/helm/ks_microservice.py
Labels: Review effort 2/5

#655 feat: update system test mapping for SBOM testing and remove producti…
  system_test_mapping.json
Labels: Review effort 1/5

#656 fix: update expected prices for monthly and yearly subscriptions
  configurations/system/tests_cases/payments_tests.py
Labels: Review effort 1/5

#642 Feature/node agent systests
  configurations/cdr_mock/cdr.json
  configurations/k8s_workloads/deployments/redis_sleep_long/redis-sleep-long.yaml
  configurations/system/backends.py
  configurations/system/tests_cases/runtime_tests.py
  create_env.sh
  infrastructure/backend_api.py
  infrastructure/kubectl_wrapper.py
  readme.md
  system_test_mapping.json
  systest_utils/statics.py
  tests_scripts/runtime/alerts.py
  tests_scripts/runtime/cadr.py
  tests_scripts/runtime/consts.py
  tests_scripts/runtime/incidents.py
  tests_scripts/runtime/policies.py
  tests_scripts/runtime/response.py
Labels: Review effort 3/5

#657 ka
  tests_scripts/accounts/cspm_test_models.py
Labels: Review effort 1/5

#658 fix relevancy_large_image
  configurations/expected-result/SBOM/redis_incomplete.json
  tests_scripts/helm/relevant_cve.py
  tests_scripts/kubernetes/base_k8s.py
Labels: Review effort 2/5

#660 fix workload name filter
  tests_scripts/helm/jira_integration.py
  tests_scripts/helm/vuln_scan.py
Labels: Review effort 2/5
